language: bash
before_install:
  - scversion="stable" # or "v0.4.7", or "latest"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }
  - export PATH=$PATH:/shellcheck-$scversion/
script: 
  - shellcheck *.sh
